name: 'Helm Chart Docs Github Pages'
branding:
  icon: 'activity'
  color: 'blue'
description: 'This Action will generate your static Helm Chart Docs and deploy it to Github Pages'
inputs:
  token:
    description: 'Your Github token'
    required: true
  commitMessage:
    description: 'Your git commit message'
    required: false
    default: 'Deploy Helm Charts Docs'
  branch:
    description: 'Your git commit message'
    required: false
    default: 'gh-pages'
  helmRepository:
    description: 'Docker image version'
    required: false
    default: 'omegion'
  helmRepositoryUrl:
    description: 'Docker image version'
    required: false
    default: 'https://charts.omegion.dev'
  dockerImageVersion:
    description: 'Docker image version'
    required: false
    default: 'v0.14.0'
runs:
  using: composite
  steps:
    - name: Build and generate nuxt
      run: |
        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

        git config --global user.email "$owner@users.noreply.github.com"
        git config --global user.name "$owner"

        git checkout -f ${{ inputs.branch }}
        docker run \
          --build-arg GITHUB_REPO=$repo \
          --build-arg HELM_REPO_NAME=${{ inputs.helmRepository }} \
          --build-arg HELM_REPO_URL=${{ inputs.helmRepositoryUrl }} \
          -v $(pwd)/dist:/src/dist \
          -v $(pwd)/index.yaml:/src/index.yaml ghcr.io/omegion/helm-charts-docs:${{ inputs.dockerImageVersion }}
        sudo cp -r dist/* $(pwd)
        sudo rm -r dist src || true

        git add -A
        git commit --allow-empty -m '${{ inputs.commitMessage }}'
        git push origin ${{ inputs.branch }}
      shell: bash
