name: 'Helm Chart Docs Github Pages'
branding:
  icon: 'activity'
  color: 'blue'
description: 'This Action will generate your static Helm Chart Docs and deploy it to Github Pages'
inputs:
  token:
    description: 'Your Github token'
    required: true
  commitMessage:
    description: 'Your git commit message'
    required: false
    default: 'Deploy Helm Charts Docs'
runs:
  using: composite
  steps:
    - name: Build and generate nuxt
      run: |
        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

        git config --global user.email "$owner@users.noreply.github.com"
        git config --global user.name "$owner"

        if [ "none" !=  ${{ inputs.cname }} ]; then echo '${{ inputs.cname }}' > CNAME; fi

        docker run ghcr.io/omegion/helm-charts-docs:v0.7.0 ls

        cd src
        yarn install
        yarn generate

        cd dist
        git init
        git add -A
        git commit -m '${{ inputs.commitMessage }}'
        git push -f https://"$owner":${{ inputs.token }}@github.com/"$owner"/"$repo".git master:gh-pages
      shell: bash