on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: fregante/setup-git-user@v1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@master
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          username: 'omegion'
          reponame: 'helm-charts-docs'
          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"